name: AI Issue Responder

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate AI response
        uses: CloudCompile/AI-Issue-Pollinations@v1.0.1   # reference your action repo + tag
        id: ai
        with:
          file-to-scan: 'README.md'  # file from the target repo
          model: 'openai'

      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            🤖 **AI Assistant Response:**
            ${{ steps.ai.outputs.ai-response }}
            _Generated automatically by Pollinations AI 🌸_
