name: AI Issue Responder

on:
  issues:
    types: [opened]

jobs:
  auto-ai-response:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate AI response using Pollinations
      - name: Generate AI response
        id: ai
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"

          # Build prompt
          PROMPT="You are a helpful GitHub assistant. Someone opened an issue titled '$TITLE' with description: '$BODY'. Suggest possible causes and fixes in a friendly tone."

          # URL-encode the prompt
          ENCODED_PROMPT=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$PROMPT")

          # Call Pollinations API via GET request
          RESPONSE=$(curl -s "https://text.pollinations.ai/$ENCODED_PROMPT?model=openai")

          # Save AI response for next step
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Step 2: Comment on the issue with AI response
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            🤖 **AI Assistant Response:**
            ${{ steps.ai.outputs.response }}

            _Generated automatically by Pollinations AI 🌸_
